#!/bin/sh

# Check for root permissions
if [ `id -u` != 0 ]; then
	echo "You must be root to run this."
	exit 0
fi

swapfile="/var/swap"
backupdate="$(date +%Y%m%d)"
backupfstab="/tmp/fstab-$(backupdate)"

# Check for current swap space
echo -n "Checking for swap space..."
if [ "$(free -h | grep Swap | awk '{print $2}')" != "0B" ]; then
	echo "OK"
	echo "You currently have $(free -h | grep Swap | awk '{print $2}') swap space."
	echo "Current swap space is located at $(swapon | tail -n1 | awk '{print $1}')."
	echo "/etc/fstab entry:"
	grep -i swap /etc/fstab
	exit 0
else
	echo "OK"
	echo "No swap space detected."
	if grep -q -i swap /etc/fstab; then
		echo -n "Backing up /etc/fstab to ${backupfstab}..."
		cp /etc/fstab ${backupfstab}
		grep -v swap ${backupfstab} > /etc/fstab
		echo "OK"
	fi
fi

# Make swap space
echo -n "Creating swap file..."
dd if=/dev/zero of=${swapfile} bs=4M count=2048 2>/dev/null
if [ $? != 0 ]; then
	echo "ERROR"
	echo "Check the destination directory filename and permissions."
	exit 1
else
	echo "OK"
fi
echo -n "Changing swap permissions to 0600..."
chmod 0600 ${swapfile}
if [ $? != 0 ]; then
	echo "ERROR"
	exit 1
else
	echo "OK"
fi
echo -n "Making swap..."
mkswap ${swapfile} 1>/dev/null
if [ $? != 0 ]; then
	echo "ERROR"
	exit 1
else
	echo "OK"
fi
echo -n "Adding swapfile to /etc/fstab..."
echo -e "${swapfile}\tswap\tswap\tdefaults,sw\t0\t0" >> /etc/fstab
if [ $? != 0 ]; then
	echo "ERROR"
	exit 1
else
	echo "OK"
fi
echo -n "Turning on swap..."
swapon -a
if [ $? != 0 ]; then
	echo "ERROR"
	exit 1
else
	echo "OK"
fi
echo -n "Checking swap..."
if [ "$(free -h | grep Swap | awk '{print $2}')" == "0B" ]; then
	echo "ERROR"
	echo "There was an error in creating swap space. Please check the commands run and try again."
	exit 1
else
	echo "OK"
fi
echo "You have $(free -h | grep Swap | awk '{print $2}') of swap space."
echo "Swapfile written to $(swapon | tail -n1 | awk '{print $1}')"
exit 0
